### PR TITLE
Add remote storage

### PR DESCRIPTION
**Pull request by vaughansharman**
The existing implementation uses local storage in the browser, but this version adds a new implementation of the TodoStore interface "RemoteTodoStore". This is a very basic implementation that calls the Scala backend to either GET or PUT the current list

Please bear in mind that this is purely for the purposes of being a stub project to speed up initial development and I would not suggest structuing the front end and server in this fashion in a real application. The work done does however give examples of how to:

1) Add scala routes
2) Add Models
3) Add json serialisation of models
4) Calling http endpoints from Angular 2
5) How to test scala code

This PR sets the default storage to be Remote but it can easily be flicked back to be Local by modifying the bootstrap.ts file.

### CODE REVIEW

**Comment by joost-de-vries** [comment]
Hi Vaughn,

I'll have a look at your code.
My initial thinking was that this project is mostly about how to do NG2+Typescript+Play. And not so much about how to setup a great NG2 application. Or even the quality of the NG2 application itself.
Having said that there's probably no harm in adding some server interaction.
I'll be away the coming week.
I'll probably have a look after.

**Comment by vaughansharman** [comment]
Cheers

I think by adding the Scala endpoints it makes more of a compelling template. Without the endpoints the only thing play is really doing is serving up static html...

**Comment by joost-de-vries** [comment]
I've just upgraded the demo project to Angular RC4.
I think it'd be a good idea to upgrade this code to RC4 before merging the pull request.
Do you agree?

**Comment by vaughansharman** [comment]
Yep, good call, i'll have it ready for you this weekend or early next week

**Comment by vaughansharman** [comment]
Did you push you RC4 changes? I just did a revers merge and can't see any recent RC4 changes...

**Comment by joost-de-vries** [comment]
Those changes are in the ts_20_preview branch.
I'm thinking of merging that to master. But ideally I'd like to wait for typescript 2.0 to become final.

**Comment by vaughansharman** [comment]
Ahh, ok

I don't see any problem merging the most recent RC to master now. The final may still be a while off... Obviously your call though, it's your repo.

**Comment by golechwierowicz** [comment]
Now that RC5 is released, maybe it would be useful to rewrite this?

**Comment by joost-de-vries** [comment]
Hey, just wanted to let you know that the angular2 demo application has been switched from todomvc to tour of heroes, Since that's _the_ canonical angular2 demo application now. Have a look.

**Pull request closed without merging**
